services:
  postgres:
    image: 'postgres:16.0-alpine'
    environment:
      - 'POSTGRES_DB=${PG_DB_NAME}'
      - 'POSTGRES_PASSWORD=${PG_PASSWORD}'
      - 'POSTGRES_USER=${PG_USERNAME}'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    networks:
      MenuStreamNetwork:
        aliases:
            - 'postgres'

#  rabbitmq:
#    image: 'rabbitmq:4.0-rc-alpine'
#    environment:
#      - 'RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}'
#      - 'RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}'
#    ports:
#      - '5672:5672'
#    expose:
#      - '5672'
#    networks:
#      MenuStreamNetwork:
#
#        aliases:
#          - 'rabbitmq'

networks:
  MenuStreamNetwork:
    driver: bridge
